### PR TITLE
Wallofcoins Buying Wizard

### PR DESCRIPTION
**Pull request by robertgenito**
Introduces Wall of Coins functionality:

* Able to Buy Dash with Cash nearby.
* Address Book associates addresses with the Wall of Coins Order.
* "Passwordless" user on-boarding experience.
* Every page alerts the end user that help and support is available via live chat and over the phone. (We supply a web link to the live chat and the phone number to call support directly!)
* Easy "un-linking" phone number from device.

woc-dash-01
woc-dash-02
woc-dash-03-edit
woc-dash-04

### CODE REVIEW

**Comment by rgenito** [comment]
Hi @QuantumExplorer ! We can also set HashEngineering as a reviewer (or whomever you want to invite) once he accepts the invitation to the team.

**Comment by HashEngineering** [comment]
The branch to merge against is "master" which is not present on this repo.  Updating of dash-12.1 was stopped in April 2017, about 9 months ago.  A rebase will be required as the github tools indicate that this pull request cannot be automatically merged with master.

**Comment by rgenito** [comment]
@HashEngineering thank you. I have changed the base to the current "master" on HashEngineering/dash-wallet. Please review when you can and if there are any changes we must make internally, just let me know and it will be done. Thank you! :)

**Comment by HashEngineering** [comment]
The command to use is 'git rebase master'.

The rebase will generate many merge conflicts, as seen on this page in terms of which files will require fixing.  Some of them may be minor fixes, related to formatting.  Others will include more work, like ExchangeRatesProvider, which was changed a lot in our updates and this code will need to be redone by your developers to some degree.

**Comment by HashEngineering** [comment]
I built the app today and found that the app does not connect to the Dash Network due to recent Dash Network upgrades.  

What kind of testing (both production and testnet) has been done?  If the app is run under the testnet, is it possible to buy testnet coins using "simulated" purchases?  Running under testnet, looking to buy 1 DASH, I found two sellers that were local.  Where these real or imaginary?

Is there documentation that shows how to use the Wall-of-coins services within the app?

**Comment by rgenito** [comment]
This branch is being deprecated.

**Pull request closed without merging**
